import { Box } from "@chakra-ui/react";
import Head from "next/head";
import SideBar from "../src/components/layout/nav/SideBar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>ChatApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box h="100vh">
        <SideBar />
      </Box>
    </div>
  );
}
